---
title: "Theory"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Theory}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(psvar)
```
# Methodology

Let   $Y_t$  be  an  n×1  vector  of  observables.  We  assume  that  the  dynamics  of  the  observables are described by a system of linear simultaneous equations

$$
 A Y _ { t } = \sum _ { j = 1 } ^ { p } \alpha _ { j } Y _ { t - j } + \varepsilon _ { t } 
$$


$$
 Y _ { t } = \sum _ { j = 1 } ^ { p } \delta _ { j } Y _ { t - j } + B \varepsilon _ { t } 
$$

$$ u_t =  B \epsilon_t $$

$$
 E ( u _ { t } u _ { t } ^ { \prime } ) = B B ^ { \prime } = \Sigma _ { u } 
$$

$$ 
\left[ 
  \begin{array} 
    { c } { u _ { 1 , t } } \\ { ( k \times 1 ) } \\ { u _ { 2 , t } } \\ { ( N - k \times 1 ) } 
  \end{array} \right] = 
 \left[ 
  \begin{array} { c c } { \beta_{ 11 } } & { \beta_{ 12 } } \\ { ( k \times k ) } & { ( k \times N - k ) } \\ { \beta _ { 21 } } & { \beta _ { 22 } } \\ { ( N - k \times k ) } & { ( N - k \times N - k ) } 
 \end{array} \right] \left[ 
    \begin{array}{c} 
    { \epsilon _ { 1 , t } } \\ { ( k \times 1 ) } \\ { \epsilon _ { 2 , t } } \\ { ( N - k \times 1 ) } 
    \end{array} 
  \right] 
$$
  
  
Consider the following partitioning of B:

$$
 B = \left[ \begin{array} { c c } { \beta _ { 1 } } & { \beta _ { 2 } } \\ { n \times k } & { n \times ( n - k ) } \end{array} \right], \quad \beta _ { 1 } = \left[ \begin{array} { c c } { \beta _ { 11 } ^ { \prime } } & { \beta _ { 21 } ^ { \prime } } \\ { k \times k } & { k \times ( n - k ) } \end{array} \right] ^ { \prime } , \quad \beta _ { 2 } = \left[ \begin{array} { c c } { \beta _ { 12 } ^ { \prime } } & { \beta _ { 22 } ^ { \prime } } \\ { ( n - k ) \times k } & { ( n - k ) \times ( n - k ) } \end{array} \right] ^ { \prime } 
$$



$$
 \beta _ { 21 } = ( \Sigma _ { mu _ { 1 } } ^ { - 1 } \Sigma _ { mu _ { 2 } ^ { \prime } } ) ^ { \prime } \beta _ { 11 } 
$$


$$
 \left. \begin{array} { l } 
 { \beta _ { 21 } \beta _ { 11 } ^ { - 1 } = ( \Sigma _ { mu 1 } ^ { - 1 } \Sigma _ { mu _ { 2 } ^ { \prime } } ) ^ { \prime } } \\  { \beta _ { 12 } \beta _ { 22 } ^ { - 1 } = ( \beta _ { 12 } \beta _ { 12 } ^ { \prime } ( \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ) ^ { \prime } + ( \Sigma _ { 21 } - \beta _ { 21 } \beta _ { 11 } ^ { - 1 } \Sigma _ { 11 } ) ^ { \prime } ) ( \beta _ { 22 } \beta _ { 22 } ^ { \prime - 1 } ) }\\ { \beta _ { 12 } \beta _ { 12 } ^ { \prime } = ( \Sigma _ { 21 } - \beta _ { 21 } \beta _ { 11 } ^ { - 1 } \Sigma _ { 11 } ) ^ { \prime } Z ^ { - 1 } ( \Sigma _ { 21 } - \beta _ { 21 } \beta _ { 11 } ^ { - 1 } \Sigma _ { 11 } ) } \\ { \beta _ { 22 } \beta _ { 22 } ^ { \prime } = \Sigma _ { 22 } + \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ( \beta _ { 12 } \beta _ { 12 } ^ { \prime } - \Sigma _ { 11 } ) ( \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ) ^ { \prime } } \\ { \beta _ { 11 } \beta _ { 11 } ^ { \prime } = \Sigma _ { 11 } - \beta _ { 12 } \beta _ { 12 } ^ { \prime } } \end{array} \right. 
$$

$$
 Z = \beta _ { 21 } \beta _ { 11 } ^ { - 1 } \Sigma _ { 11 } ( \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ) ^ { \prime } - ( \Sigma _ { 21 } ( \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ) ^ { \prime } + \beta _ { 21 } \beta _ { 11 } ^ { - 1 } \Sigma _ { 21 } ^ { \prime } ) + \Sigma _ { 22 } 
$$



$$
 \left. \begin{array}{l}{ \beta _ { 11 } S _ { 1 } ^ { - 1 } = ( I - \beta _ { 12 } \beta _ { 22 } ^ { - 1 } \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ) ^ { - 1 } }\\{ \beta _ { 21 } S _ { 1 } ^ { - 1 } = \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ( I - \beta _ { 12 } \beta _ { 22 } ^ { - 1 } \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ) ^ { - 1 } }\\{ S _ { 1 } S _ { 1 } ^ { \prime } = ( I - \beta _ { 12 } \beta _ { 22 } ^ { - 1 } \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ) \beta _ { 11 } \beta _ { 11 } ^ { \prime } ( I - \beta _ { 12 } \beta _ { 22 } ^ { - 1 } \beta _ { 21 } \beta _ { 11 } ^ { - 1 } ) }\end{array} \right. 
$$